spark.sql.extensions                   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.iceberg              org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.catalog-impl org.apache.iceberg.jdbc.JdbcCatalog
spark.sql.catalog.iceberg.uri          jdbc:postgresql://postgres:5432/maritime_logistics
spark.sql.catalog.iceberg.jdbc.user    postgres
spark.sql.catalog.iceberg.jdbc.password postgres
spark.sql.catalog.iceberg.warehouse    s3a://tidaline-lakehouse/
spark.sql.catalog.iceberg.io-impl      org.apache.iceberg.aws.s3.S3FileIO
spark.hadoop.fs.s3a.endpoint           http://minio:9000
spark.hadoop.fs.s3a.access.key         minioadmin
spark.hadoop.fs.s3a.secret.key         minioadmin
spark.hadoop.fs.s3a.path.style.access  true
spark.hadoop.fs.s3a.impl               org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider
